obj-$(CONFIG_DUAGON_BACKPLANE)	+= core.o looptest.o debugfs.o cards.o serial.o rpc.o fifo.o backplane.o

# protocols
obj-$(CONFIG_DUAGON_BACKPLANE)	+= proto-log.o
obj-$(CONFIG_DUAGON_BACKPLANE)	+= proto-io.o

# card drivers
obj-$(CONFIG_DUAGON_BACKPLANE)	+= card-i701.o
obj-$(CONFIG_DUAGON_BACKPLANE)	+= card-i202.o
obj-$(CONFIG_DUAGON_BACKPLANE)	+= card-i012.o
