obj-$(CONFIG_DUAGON_BACKPLANE)	+= core.o looptest.o debugfs.o cards.o serial.o rpc.o log.o fifo.o backplane.o

# card drivers
obj-$(CONFIG_DUAGON_BACKPLANE)	+= i701.o
obj-$(CONFIG_DUAGON_BACKPLANE)	+= i202.o
obj-$(CONFIG_DUAGON_BACKPLANE)	+= i012.o
