obj-$(CONFIG_IONIA_BACKPLANE)	+= core.o looptest.o debugfs.o cards.o serial.o rpc.o fifo.o backplane.o proto-ctrl.o

# protocols
obj-$(CONFIG_IONIA_PROTO_LOG)	+= proto-log.o
obj-$(CONFIG_IONIA_PROTO_DIO)	+= proto-dio.o

# card drivers
obj-$(CONFIG_IONIA_I701)	+= card-i701.o
obj-$(CONFIG_IONIA_I202)	+= card-i202.o
obj-$(CONFIG_IONIA_I012)	+= card-i012.o
