/*
 * AM33XX SDMA channel definitions
 *
 * This file is automatically generated from the AM33XX hardware databases.
 *
 * Copyright (C) 2011 Texas Instruments Incorporated - http://www.ti.com/
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation version 2.
 *
 * This program is distributed "as is" WITHOUT ANY WARRANTY of any
 * kind, whether express or implied; without even the implied warranty
 * of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */

#ifndef __ARCH_ARM_MACH_OMAP2_AM33XX_DMA_H
#define __ARCH_ARM_MACH_OMAP2_AM33XX_DMA_H

#define AM33XX_DMA_MCASP0_X				8
#define AM33XX_DMA_MCASP0_R				9
#define AM33XX_DMA_MCASP1_X				10
#define AM33XX_DMA_MCASP1_R				11

#endif
